"""Add game state fields

Revision ID: 056a9222239b
Revises: acd74a81dd80
Create Date: 2025-10-07 20:40:39.728166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056a9222239b'
down_revision = 'acd74a81dd80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revealed', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('flagged', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('status')
        batch_op.drop_column('flagged')
        batch_op.drop_column('revealed')

    # ### end Alembic commands ###
